// Generated by scripts/gds-tokens.mjs. Do not edit by hand.
// Source: Figma "Global Design System", Semantics collection.

export const GDS_TOKEN_COUNT = 161;
export const GDS_MODES = ["TPO","Netflu","FF","EM","OD","Prensa Dark","TW"] as const;
export const GDS_BRANDS = ["The Playoffs","Netflu","The Football Faithful","Estado de Minas","Olhar Digital","Prensa Futbol","Toffee Web"] as const;
/** color/primary/base per brand, for the brand buttons. */
export const GDS_PRIMARY = ["#002699","#8B002F","#5C11A6","#20284A","#111829","#273A68","#0C2C61"] as const;
