// Generates the brand CSS and data for the live GDS Match Card from the
// token export used by the GDS video (Figma "Semantics" collection).
// Usage: node scripts/gds-tokens.mjs [path/to/tokens.js]

import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import os from "node:os";

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const source = process.argv[2] ?? path.join(os.homedir(), "Desktop/idea/gds-video/tokens.js");

const sandbox = { window: {} };
vm.runInNewContext(fs.readFileSync(source, "utf8"), sandbox);
const G = sandbox.window.GDS;
if (!G?.modes || !G?.vars) throw new Error(`No GDS tokens found in ${source}`);

// Brand fonts loaded with next/font (see src/lib/gds-fonts.ts). Families not
// listed here fall back to their own name and then to sans-serif.
const FONT_VARS = {
  "Plus Jakarta Sans": "--font-gds-jakarta",
  "Work Sans": "--font-gds-work",
  Poppins: "--font-gds-poppins",
  Inter: "--font-gds-inter",
  "Barlow Condensed": "--font-gds-barlow",
  "IBM Plex Sans": "--font-gds-plex",
  "Space Grotesk": "--font-gds-grotesk",
};

// Same conversion as the video: colours as is, strings quoted, weights and
// opacities unitless, every other number in px.
const unitless = (name) => /weight|opacity/.test(name);
const cssName = (name) => `--t-${name.replace(/\//g, "-").replace(/[^a-zA-Z0-9_-]/g, "-")}`;
function cssValue(name, type, value) {
  if (type === "C") return value;
  if (type === "S") {
    const v = FONT_VARS[value];
    // The fallback inside var() keeps the declaration valid even where the
    // next/font variable is not defined.
    return v ? `var(${v}, "${value}"), sans-serif` : `"${value}", sans-serif`;
  }
  return unitless(name) ? String(value) : `${value}px`;
}

let css = `/* Generated by scripts/gds-tokens.mjs from the Figma "Global Design System"
   Semantics collection: ${G.vars.length} variables, ${G.modes.length} brands. Do not edit. */\n`;
G.modes.forEach((mode, m) => {
  css += `\n/* ${mode} */\n.gds-m${m} {\n`;
  for (const [name, type, values] of G.vars) css += `  ${cssName(name)}: ${cssValue(name, type, values[m])};\n`;
  css += "}\n";
});

const primary = G.vars.find(([n]) => n === "color/primary/base")[2];
const ts = `// Generated by scripts/gds-tokens.mjs. Do not edit by hand.
// Source: Figma "Global Design System", Semantics collection.

export const GDS_TOKEN_COUNT = ${G.vars.length};
export const GDS_MODES = ${JSON.stringify(G.modes)} as const;
export const GDS_BRANDS = ${JSON.stringify(G.brands)} as const;
/** color/primary/base per brand, for the brand buttons. */
export const GDS_PRIMARY = ${JSON.stringify(primary)} as const;
`;

fs.writeFileSync(path.join(root, "src/components/gds/gds-modes.css"), css);
fs.writeFileSync(path.join(root, "src/lib/gds-tokens.ts"), ts);
console.log(`GDS: ${G.vars.length} tokens x ${G.modes.length} brands -> gds-modes.css + gds-tokens.ts`);
